#!/usr/bin/env python3
"""
Installation and setup script for n8n Workflow Manager
Creates symlinks and shell aliases for convenient access
"""

import os
import sys
import stat
from pathlib import Path
from typing import List, Dict


class n8n_deploy_Installer:
    """Installer for n8n Workflow Manager"""

    def __init__(self):
        self.project_root = Path(__file__).parent.absolute()
        self.home_dir = Path.home()
        self.bin_dir = self.home_dir / ".local" / "bin"
        self.shell_rc_files = [
            self.home_dir / ".bashrc",
            self.home_dir / ".zshrc",
            self.home_dir / ".profile",
        ]

    def create_symlinks(self) -> bool:
        """Create symlinks for easy command access"""
        print("🔗 Creating symlinks...")

        # Ensure .local/bin directory exists
        self.bin_dir.mkdir(parents=True, exist_ok=True)

        # Check if .local/bin is in PATH
        if str(self.bin_dir) not in os.environ.get("PATH", ""):
            print(f"⚠️  Warning: {self.bin_dir} is not in your PATH")
            print(f"   Add this line to your shell rc file:")
            print(f'   export PATH="{self.bin_dir}:$PATH"')

        symlinks = [
            ("n8n-deploy", self.project_root / "api" / "cli.py"),
        ]

        success = True
        for link_name, target in symlinks:
            link_path = self.bin_dir / link_name

            try:
                # Remove existing symlink/file
                if link_path.exists() or link_path.is_symlink():
                    link_path.unlink()

                # Create symlink
                link_path.symlink_to(target)

                # Make target executable
                target.chmod(target.stat().st_mode | stat.S_IEXEC)

                print(f"  ✅ Created symlink: {link_name} -> {target}")

            except Exception as e:
                print(f"  ❌ Failed to create symlink {link_name}: {e}")
                success = False

        return success

    def create_shell_aliases(self) -> bool:
        """Create shell aliases in rc files"""
        print("🐚 Creating shell aliases...")

        aliases = {
            # Main command (short and memorable)
            "n8n-deploy": f"python3 {self.project_root}/api/cli.py",
            # Essential workflow commands
            "n8n-deploy-list": f"python3 {self.project_root}/api/cli.py list",
            "n8n-deploy-pull": f"python3 {self.project_root}/api/cli.py pull",
            "n8n-deploy-push": f"python3 {self.project_root}/api/cli.py push",
            # Essential backup commands
            "n8n-deploy-backup-workflows": f"python3 {self.project_root}/api/cli.py backup-workflows",
            "n8n-deploy-restore-workflows": f"python3 {self.project_root}/api/cli.py restore-workflows",
            # Essential database commands
            "n8n-deploy-init": f"python3 {self.project_root}/api/cli.py db init",
            "n8n-deploy-status": f"python3 {self.project_root}/api/cli.py db status",
        }

        # Alias block to add to shell rc files
        alias_block = f"""
# 🎭 n8n Workflow Manager Aliases
# Generated by n8n_deploy_ installer on {Path(__file__).stat().st_mtime}

"""
        for alias_name, command in aliases.items():
            alias_block += f"alias {alias_name}='{command}'\n"

        alias_block += f"""
# Add n8n_deploy_ to PATH if not already there
if [[ ":$PATH:" != *":{self.bin_dir}:"* ]]; then
    export PATH="{self.bin_dir}:$PATH"
fi

"""

        success = True
        for rc_file in self.shell_rc_files:
            if not rc_file.exists():
                continue

            try:
                # Read existing content
                content = rc_file.read_text() if rc_file.exists() else ""

                # Remove existing n8n_deploy_ aliases
                lines = content.split("\n")
                new_lines = []
                skip_section = False

                for line in lines:
                    if "🎭 n8n Workflow Manager Aliases" in line:
                        skip_section = True
                        continue
                    elif skip_section and line.strip() == "":
                        # Empty line might indicate end of section
                        if not any(
                            keyword in line
                            for keyword in [
                                "alias n8n-deploy",
                                "alias n8n-deploy",
                                "alias itzam-n8n",
                            ]
                        ):
                            skip_section = False
                    elif (
                        skip_section
                        and not line.startswith("alias ")
                        and not line.startswith("export PATH")
                        and not line.startswith("#")
                    ):
                        skip_section = False

                    if not skip_section:
                        new_lines.append(line)

                # Add new aliases
                new_content = "\n".join(new_lines).rstrip() + "\n" + alias_block

                # Write back
                rc_file.write_text(new_content)
                print(f"  ✅ Updated aliases in: {rc_file}")

            except Exception as e:
                print(f"  ❌ Failed to update {rc_file}: {e}")
                success = False

        return success

    def install_dependencies(self) -> bool:
        """Install Python dependencies"""
        print("📦 Installing Python dependencies...")

        try:
            import subprocess

            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "-r",
                    str(self.project_root / "requirements.txt"),
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode == 0:
                print("  ✅ Dependencies installed successfully")
                return True
            else:
                print(f"  ❌ Failed to install dependencies: {result.stderr}")
                return False

        except Exception as e:
            print(f"  ❌ Failed to install dependencies: {e}")
            return False

    def verify_installation(self) -> bool:
        """Verify the installation works"""
        print("🧪 Verifying installation...")

        try:
            # Try importing the main module
            sys.path.insert(0, str(self.project_root))
            from api import WorkflowManager
            from api.n8n_deploy_db import n8n_deploy_DB

            # Test basic functionality
            db = n8n_deploy_DB()
            stats = db.get_database_stats()

            manager = WorkflowManager()
            workflows = manager.list_workflows()

            print(f"  ✅ n8n_deploy_ database: {len(stats.tables)} tables")
            print(f"  ✅ Workflow manager: {len(workflows)} workflows configured")

            return True

        except Exception as e:
            print(f"  ❌ Verification failed: {e}")
            return False

    def run_installation(self):
        """Run the complete installation process"""
        print("🎭 n8n Workflow Manager Installation")
        print("=" * 50)

        steps = [
            ("Installing dependencies", self.install_dependencies),
            ("Creating symlinks", self.create_symlinks),
            ("Creating shell aliases", self.create_shell_aliases),
            ("Verifying installation", self.verify_installation),
        ]

        for step_name, step_func in steps:
            print(f"\n{step_name}...")
            if not step_func():
                print(f"❌ Installation failed at: {step_name}")
                return False

        print("\n🎉 Installation completed successfully!")
        print("\nNext steps:")
        print("1. Restart your shell or run: source ~/.bashrc (or ~/.zshrc)")
        print("2. Test the installation: n8n-deploy --help")
        print("3. Initialize the database: n8n-deploy-init")
        print("4. List available workflows: n8n-deploy-list")
        print("\n📁 Base Folder Configuration:")
        print("   • Use --base-folder to specify data directory")
        print("   • Set N8N_BASE_FOLDER environment variable")
        print("   • Examples:")
        print("     n8n-deploy --base-folder /path/to/project list")
        print("     export N8N_BASE_FOLDER=/home/user/my-workflows")

        return True

    def uninstall(self):
        """Remove n8n_deploy_ installation"""
        print("🗑️  Uninstalling n8n Workflow Manager...")

        # Remove symlinks
        for link_name in ["n8n-deploy"]:
            link_path = self.bin_dir / link_name
            if link_path.exists():
                link_path.unlink()
                print(f"  ✅ Removed symlink: {link_name}")

        # Remove aliases from shell rc files
        for rc_file in self.shell_rc_files:
            if not rc_file.exists():
                continue

            try:
                content = rc_file.read_text()
                lines = content.split("\n")
                new_lines = []
                skip_section = False

                for line in lines:
                    if "🎭 n8n Workflow Manager Aliases" in line:
                        skip_section = True
                        continue
                    elif skip_section and line.strip() == "":
                        skip_section = False
                    elif skip_section:
                        continue

                    if not skip_section:
                        new_lines.append(line)

                new_content = "\n".join(new_lines)
                rc_file.write_text(new_content)
                print(f"  ✅ Cleaned aliases from: {rc_file}")

            except Exception as e:
                print(f"  ❌ Failed to clean {rc_file}: {e}")

        print("✅ Uninstallation completed")


def main():
    """Main installation script"""
    installer = n8n_deploy_Installer()

    if len(sys.argv) > 1 and sys.argv[1] == "uninstall":
        installer.uninstall()
    else:
        installer.run_installation()


if __name__ == "__main__":
    main()
