source 'https://rubygems.org'

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.8.0"
gem "webrick", "~> 1.8"  # Required for Ruby 3.0+

# GitHub Pages plugins (for SEO and compatibility)
group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
